# TODO: Remove bellow once SchemaStore/schemastore/#4525 is merged
packages:
  - .

onlyBuiltDependencies:
  - '@vscode/vsce-sign'
  - esbuild
  - keytar

patchedDependencies:
  tsup: patches/tsup.patch
